### ISSUE TITLE
type checks assertions doesn't seem to be safe

### ISSUE THREAD

**Issue by kefirski** [VKCOM/YouTokenToMe#42]
Current type check assertions look weird

```python
    def decode(self, ids):
        assert isinstance(ids, list)
        if len(ids) > 0 and isinstance(ids[0], int):
            ids = [ids]
        cdef vector[string] sentences
        cdef Status status = self.encoder.decode(ids, &sentences)
        if status.code != 0:
            raise ValueError(status.message.decode())
        return [sentence.decode() for sentence in sentences]
```

There is no any error message after checking that `ids` is a `list` instance. Also, checking the first element doesn't seem to be type-safe since the passed list could be heterogeneous. 

Here is a simple example of the way somebody could break it:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    model.decode([[1, 5, 6, 7, "2"]])
  File "/Users/d.gavrilov/YouTokenToMe/youtokentome/youtokentome.py", line 80, in decode
    return self.bpe_cython.decode(ids)
  File "youtokentome/cpp/yttm.pyx", line 139, in _youtokentome_cython.BPE.decode
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_int
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_int
TypeError: an integer is required
```

Is there any real reason to perform this type check if we still could workaround it?

**Comment by kefirski** [comment]
Fixed in #43
